name: xrecon
channels:
  - conda-forge
  - astra-toolbox/label/dev
  - defaults
dependencies:
  - scipy
  - py-opencv
  - numpy
  - matplotlib
  - astra-toolbox
  - tomopy
  - scikit-image
  - h5py
  - ipyvolume
  - jupyter
  - ipython
  - nbformat
  - python=3
  - pyqt
  - tqdm
  - autopep8
  - pylint
  - ipywidgets
  - jupytext
  - pip  
  - pip:
    - pymongo
