name: xrecon
channels:
  - conda-forge
  - astra-toolbox
  - defaults
dependencies:
  - scipy
  - py-opencv
  - numpy
  - matplotlib
  - astra-toolbox
  - tomopy
  - scikit-image
  - h5py
  - ipyvolume
  - jupyter
  - ipython
  - nbformat
  - python=3.9
  - pyqt
  - tqdm
  - autopep8
  - pylint
  - ipywidgets
  - jupytext
  - pip
  - zarr
  - dask
  - cupy
  - pillow
  - k3d
  - pip:
    - pymongo==3
    - imreg_dft
    - pyvista
