name: xrecon
channels:
  - conda-forge
  - astra-toolbox
  - nvidia
  - https://software.repos.intel.com/python/conda
  - ccpi
  - httomo 
dependencies:
  - python=3.11
  - scipy
  - py-opencv
  - numpy
  - matplotlib
  - astra-toolbox=*=cuda*
  - cil=25.0.0
  - ipp=2021.12
  - ccpi-regulariser
  - tigre
  - tomopy
  - scikit-image
  - h5py
  - requests
  - jupyter
  - jupyterlab
  - ipython
  - nbformat
  - pyqt
  - tqdm
  - autopep8
  - pylint
  - ipywidgets
  - jupytext
  - dask
  - pillow
  - k3d
  - scikit-learn
  - pip
  - pip:
    - pymongo==4
    - git+https://github.com/matejak/imreg_dft.git
    - pyvista
    - line_profiler
    - cupy-cuda12x
